
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sarowar_saurav
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    public Invoice() {
        initComponents();
    }
    public Connection getConnection() {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login-database", "root", "");
            return con;
        } catch (SQLException e) {
            return null;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFullNameLabel2 = new javax.swing.JLabel();
        jCustomerID1 = new javax.swing.JTextField();
        jFullNameLabel = new javax.swing.JLabel();
        jOrderID1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jInvoiceText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jFullNameLabel2.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel2.setText("Customer ID :");
        jFullNameLabel2.setToolTipText("");

        jCustomerID1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCustomerID1.setText("Customer ID");
        jCustomerID1.setToolTipText("");
        jCustomerID1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jCustomerID1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCustomerID1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCustomerID1FocusLost(evt);
            }
        });

        jFullNameLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel.setText("Order ID  :");
        jFullNameLabel.setToolTipText("");

        jOrderID1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jOrderID1.setText("Order ID");
        jOrderID1.setToolTipText("");
        jOrderID1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jOrderID1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jOrderID1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jOrderID1FocusLost(evt);
            }
        });

        jInvoiceText.setEditable(false);
        jInvoiceText.setColumns(20);
        jInvoiceText.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jInvoiceText.setRows(5);
        jInvoiceText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jInvoiceText);

        jLabel1.setFont(new java.awt.Font("Bebas Kai", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INVOICE ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFullNameLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jCustomerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jOrderID1)
                        .addGap(244, 244, 244))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCustomerID1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFullNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOrderID1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCustomerID1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCustomerID1FocusGained
        // TODO add your handling code here:
        if (jCustomerID1.getText().trim().toLowerCase().equals("Customer ID")) {
            jCustomerID1.setText("");
            jCustomerID1.setForeground(Color.black);
        }
    }//GEN-LAST:event_jCustomerID1FocusGained

    private void jCustomerID1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCustomerID1FocusLost
        // TODO add your handling code here:
        if (jCustomerID1.getText().trim().equals("")
            || jCustomerID1.getText().trim().toLowerCase().equals("Customer ID")) {
            jCustomerID1.setText("Customer ID");
            jCustomerID1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jCustomerID1FocusLost

    private void jOrderID1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jOrderID1FocusGained
        // TODO add your handling code here:
        if (jOrderID1.getText().trim().toLowerCase().equals("Order ID")) {
            jOrderID1.setText("");
            jOrderID1.setForeground(Color.black);
        }
    }//GEN-LAST:event_jOrderID1FocusGained

    private void jOrderID1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jOrderID1FocusLost
        // TODO add your handling code here:
        if (jOrderID1.getText().trim().equals("")
            || jOrderID1.getText().trim().toLowerCase().equals("Order ID")) {
            jOrderID1.setText("Order ID");
            jOrderID1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jOrderID1FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField jCustomerID1;
    private javax.swing.JLabel jFullNameLabel;
    private javax.swing.JLabel jFullNameLabel2;
    public static javax.swing.JTextArea jInvoiceText;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JTextField jOrderID1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
