/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sarowar_saurav
 */
public class Login extends javax.swing.JFrame {
    

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAlready = new javax.swing.JLabel();
        jLoginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jUsernameLabel = new javax.swing.JLabel();
        jPasswordLabel = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLoginButton = new javax.swing.JButton();
        jMinimize = new javax.swing.JLabel();
        jClose = new javax.swing.JLabel();
        jNoAccount = new javax.swing.JLabel();

        jAlready.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAlready.setForeground(new java.awt.Color(255, 255, 255));
        jAlready.setText("Already have and account? Log In");
        jAlready.setToolTipText("");
        jAlready.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAlreadyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jAlreadyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jAlreadyMouseExited(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLoginPanel.setBackground(new java.awt.Color(51, 0, 51));
        jLoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setBackground(new java.awt.Color(255, 0, 51));
        jLabel1.setFont(new java.awt.Font("Bebas Kai", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Management || CSE310");
        jLabel1.setToolTipText("");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jUsernameLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsernameLabel.setText("Username :  ");
        jUsernameLabel.setToolTipText("");

        jPasswordLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPasswordLabel.setText("Password :");

        jUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jUsername.setForeground(new java.awt.Color(204, 204, 204));
        jUsername.setText("username");
        jUsername.setToolTipText("");
        jUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFocusLost(evt);
            }
        });
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });

        jPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPassword.setForeground(new java.awt.Color(204, 204, 204));
        jPassword.setText("password");
        jPassword.setToolTipText("");
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });

        jLoginButton.setBackground(new java.awt.Color(255, 102, 0));
        jLoginButton.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jLoginButton.setForeground(new java.awt.Color(0, 0, 153));
        jLoginButton.setText("Login");
        jLoginButton.setToolTipText("");
        jLoginButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLoginButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLoginButtonMouseExited(evt);
            }
        });
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginButtonActionPerformed(evt);
            }
        });

        jMinimize.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jMinimize.setForeground(new java.awt.Color(255, 255, 255));
        jMinimize.setText("_");
        jMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMinimizeMouseExited(evt);
            }
        });

        jClose.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jClose.setForeground(new java.awt.Color(255, 255, 255));
        jClose.setText("x");
        jClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jCloseMouseExited(evt);
            }
        });

        jNoAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jNoAccount.setForeground(new java.awt.Color(255, 102, 0));
        jNoAccount.setText("Don't have an account? Resgister");
        jNoAccount.setToolTipText("");
        jNoAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jNoAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNoAccountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jNoAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jNoAccountMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
        jLoginPanel.setLayout(jLoginPanelLayout);
        jLoginPanelLayout.setHorizontalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                        .addComponent(jNoAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jUsernameLabel)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(jPassword))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        jLoginPanelLayout.setVerticalGroup(
            jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jClose, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNoAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLoginPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusGained
        // TODO add your handling code here:
        if(jUsername.getText().trim().toLowerCase().equals("username"))
        {
            jUsername.setText("");
            jUsername.setForeground(Color.black);
        }
    }//GEN-LAST:event_jUsernameFocusGained

    private void jUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusLost
        // TODO add your handling code here:
        if(jUsername.getText().trim().equals("") ||
            jUsername.getText().trim().toLowerCase().equals("username"))
        {
            jUsername.setText("username");
            jUsername.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jUsernameFocusLost

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(jPassword.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            jPassword.setText("");
            jPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(jPassword.getPassword());
        if(pass.trim().equals("") ||
            pass.trim().toLowerCase().equals("password"))
        {
            jPassword.setText("password");
            jPassword.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_jPasswordFocusLost

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jLoginButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButtonMouseEntered
        // TODO add your handling code here:
        jLoginButton.setBackground(new java.awt.Color(52, 204, 255));
    }//GEN-LAST:event_jLoginButtonMouseEntered

    private void jLoginButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButtonMouseExited
        // TODO add your handling code here:
        jLoginButton.setForeground(new java.awt.Color(252, 123, 3));
        jLoginButton.setBackground(new java.awt.Color(252, 123, 3));
    }//GEN-LAST:event_jLoginButtonMouseExited

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        String user = jUsername.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login-database","root",""); 
            String sql = "select * from loginpage where username =? and password=?";
            String type ="selct type from loginpage";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, jUsername.getText());        
            pst.setString(2, String.valueOf(jPassword.getPassword()));
            ResultSet rs=pst.executeQuery();
            if("admin".equals(user) && type.equals("user")) {
             if(rs.next()){
                 
              Home_users form = new Home_users();
              form.setVisible(true);
              form.pack();
              form.setLocationRelativeTo(null);
              this.dispose();
                 
            }
             else {
                JOptionPane.showMessageDialog(null, "Username & Password not Matched!");
                jUsername.setText("");
                jPassword.setText("");
            }}
            else{
             if(rs.next()){
                 
              Home_admin form = new Home_admin();
              form.setVisible(true);
              form.pack();
              form.setLocationRelativeTo(null);
              this.dispose();
             
            
            }
             else {
                JOptionPane.showMessageDialog(null, "Logged in as customer");
                jUsername.setText("");
                jPassword.setText("");
                Home_users form = new Home_users();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                this.dispose();
            } 
            }
            con.close();
            
        } catch (HeadlessException | ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

    private void jMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimizeMouseClicked
        // TODO add your handling code here:
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jMinimizeMouseClicked

    private void jMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimizeMouseEntered
        // TODO add your handling code here:
        jMinimize.setForeground(new java.awt.Color(0, 0, 255));
    }//GEN-LAST:event_jMinimizeMouseEntered

    private void jMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMinimizeMouseExited
        // TODO add your handling code here:
        jMinimize.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jMinimizeMouseExited

    private void jCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jCloseMouseClicked

    private void jCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseEntered
        // TODO add your handling code here:
        jClose.setForeground(new java.awt.Color(0, 0, 255));
    }//GEN-LAST:event_jCloseMouseEntered

    private void jCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCloseMouseExited
        // TODO add your handling code here:
        jClose.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jCloseMouseExited

    private void jAlreadyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAlreadyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlreadyMouseClicked

    private void jAlreadyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAlreadyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlreadyMouseEntered

    private void jAlreadyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAlreadyMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jAlreadyMouseExited

    private void jNoAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoAccountMouseClicked
        // TODO add your handling code here:
        Register form = new Register();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jNoAccountMouseClicked

    private void jNoAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoAccountMouseEntered
        // TODO add your handling code here:
        jNoAccount.setForeground(new Color(52, 204, 255));
    }//GEN-LAST:event_jNoAccountMouseEntered

    private void jNoAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNoAccountMouseExited
        // TODO add your handling code here:
        jNoAccount.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_jNoAccountMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAlready;
    private javax.swing.JLabel jClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPanel jLoginPanel;
    private javax.swing.JLabel jMinimize;
    private javax.swing.JLabel jNoAccount;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JLabel jPasswordLabel;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel jUsernameLabel;
    // End of variables declaration//GEN-END:variables
}
