
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sarowar_saurav
 */
public class Orders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Orders() {
        initComponents();
        table2_update();
        table_update();
    }

    public Connection getConnection() {
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login-database", "root", "");
            return con;
        } catch (SQLException e) {
            return null;
        }
    }
    
   public void generate_invoice() {
       Invoice form = new Invoice();
       form.setVisible(true);
       form.pack();
       form.setLocationRelativeTo(null);
       Invoice.jCustomerID1.setText(jCustomerID.getText());
       Invoice.jOrderID1.setText(jOrderID.getText());
       Invoice.jInvoiceText.setText("  ============================================   INVOICE  ============================================== "
                                    + "\n"+"\n"+"Customer ID: "+jCustomerID.getText()+"\n"+"Order ID: "+ jOrderID.getText()+"\n"+"Order Date: "
                                    +"\n" + "\n" + "===================================================================================================="
                                    +"\n" + "\n"+"PR_ID"+"\t"+"\t"+"PRODUCT"+"\t"+"\t"+"QUANTITY"+"\t"+"\t"+"PRICE"+"\t"+"\t"+"TOTAL" + "\n"+"---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------" +"\n"); 
       DefaultTableModel Df3 = (DefaultTableModel) jTable3.getModel();
       int row_count = Df3.getRowCount(); int col_count = Df3.getColumnCount();
       Object [][] tableData = new Object [row_count][col_count];
       for(int i = 0 ; i < row_count ; i++)
       { 
         for(int j = 0 ; j< col_count ; j++)
         {
            tableData[i][j] = Df3.getValueAt(i, j);
            Invoice.jInvoiceText.append(tableData[i][j].toString() + "\t"+"\t");

         }
        Invoice.jInvoiceText.append("\n"+"\n");
       }
       int total = Integer.parseInt(jTotal.getText());
       Invoice.jInvoiceText.append("Total Cost + Tax: "+(total+total*0.15));
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFullName = new javax.swing.JTextField();
        jFullNameLabel1 = new javax.swing.JLabel();
        jFullNameLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jQuantity = new javax.swing.JButton();
        jOrderID = new javax.swing.JTextField();
        jCustomerID = new javax.swing.JTextField();
        jFullNameLabel = new javax.swing.JLabel();
        jFullNameLabel2 = new javax.swing.JLabel();
        jFullNameLabel4 = new javax.swing.JLabel();
        jInsert = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jShowAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTotal = new javax.swing.JTextPane();

        jFullName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFullName.setForeground(new java.awt.Color(204, 204, 204));
        jFullName.setText("fullname");
        jFullName.setToolTipText("");
        jFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFullNameFocusLost(evt);
            }
        });

        jFullNameLabel1.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel1.setText("Customer Order :");
        jFullNameLabel1.setToolTipText("");

        jFullNameLabel3.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel3.setText("Customer ID :");
        jFullNameLabel3.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(51, 0, 51));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));
        jTable2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "First Name", "Last Name", "Contact", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setColumnSelectionAllowed(true);
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(40);
        jTable2.setRowMargin(4);
        jTable2.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowGrid(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setBackground(new java.awt.Color(51, 0, 51));
        jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));
        jTable3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Name", "Quantity", "Price", "Quantity X Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setToolTipText("");
        jTable3.setColumnSelectionAllowed(true);
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(40);
        jTable3.setRowMargin(4);
        jTable3.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jTable3.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable3.setShowGrid(true);
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);
        jTable3.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jQuantity.setBackground(new java.awt.Color(255, 204, 255));
        jQuantity.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jQuantity.setText("=>");
        jQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuantityActionPerformed(evt);
            }
        });

        jOrderID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jOrderID.setToolTipText("");
        jOrderID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jOrderID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jOrderIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jOrderIDFocusLost(evt);
            }
        });

        jCustomerID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jCustomerID.setToolTipText("");
        jCustomerID.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jCustomerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jCustomerIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCustomerIDFocusLost(evt);
            }
        });

        jFullNameLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel.setText("Order ID :");
        jFullNameLabel.setToolTipText("");

        jFullNameLabel2.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel2.setText("Customer ID :");
        jFullNameLabel2.setToolTipText("");

        jFullNameLabel4.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel4.setText("Order Date :");
        jFullNameLabel4.setToolTipText("");

        jInsert.setBackground(new java.awt.Color(255, 204, 204));
        jInsert.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jInsert.setText("Insert ORDER");
        jInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertActionPerformed(evt);
            }
        });

        jClear.setBackground(new java.awt.Color(255, 204, 204));
        jClear.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jShowAll.setBackground(new java.awt.Color(255, 204, 204));
        jShowAll.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jShowAll.setText("show all orders");
        jShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShowAllActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 0, 51));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAME", "PRICE", "QUANTITY", "DESCRIPTION", "CATEGORY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Bebas Kai", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("   Total Cost : ");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTotal.setBackground(new java.awt.Color(51, 0, 51));
        jTotal.setBorder(null);
        jTotal.setCaretColor(new java.awt.Color(51, 0, 51));
        jScrollPane2.setViewportView(jTotal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFullNameLabel2)
                                        .addGap(30, 30, 30)
                                        .addComponent(jCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jFullNameLabel4)
                                                .addGap(26, 26, 26)))
                                        .addComponent(jOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(jQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(jShowAll)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFullNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jFullNameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jQuantity))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jInsert)
                            .addComponent(jShowAll)
                            .addComponent(jClear))
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(22, 22, 22))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        jCustomerID.setText(Df.getValueAt(selectedIndex, 0).toString());
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void jFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFullNameFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jFullNameFocusGained

    private void jFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFullNameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jFullNameFocusLost

    private void jOrderIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jOrderIDFocusGained
        // TODO add your handling code here:
        if (jOrderID.getText().trim().toLowerCase().equals("Order ID")) {
            jOrderID.setText("");
            jOrderID.setForeground(Color.black);
        }
    }//GEN-LAST:event_jOrderIDFocusGained

    private void jOrderIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jOrderIDFocusLost
        // TODO add your handling code here:
        if (jOrderID.getText().trim().equals("")
                || jOrderID.getText().trim().toLowerCase().equals("Order ID")) {
            jOrderID.setText("Order ID");
            jOrderID.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jOrderIDFocusLost

    private void jCustomerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCustomerIDFocusGained
        // TODO add your handling code here:
        if (jCustomerID.getText().trim().toLowerCase().equals("Customer ID")) {
            jCustomerID.setText("");
            jCustomerID.setForeground(Color.black);
        }

    }//GEN-LAST:event_jCustomerIDFocusGained

    private void jCustomerIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCustomerIDFocusLost
        // TODO add your handling code here:
        if (jCustomerID.getText().trim().equals("")
                || jCustomerID.getText().trim().toLowerCase().equals("Customer ID")) {
            jCustomerID.setText("Customer ID");
            jCustomerID.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jCustomerIDFocusLost

    private void jInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertActionPerformed
        // TODO add your handling code here:
        try {
            Connection conn = getConnection();
            PreparedStatement p =conn.prepareStatement("select *from all_orders ORDER BY Order_ID DESC LIMIT 1");
            ResultSet rs = p.executeQuery();
            rs.next();
            Integer order = rs.getInt("Order_ID");
            System.out.println(order);
            jOrderID.setText(Integer.toString(order+1));
            String order_id = jOrderID.getText();
            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            String date = jOrderID.getText();;
            String customer_id = jCustomerID.getText();
            PreparedStatement ps = conn.prepareStatement("insert into all_orders(Order_ID,Date,Customer_ID)values(?,?,?)");
            ps.setString(1, order_id);
            ps.setString(2, date);
            ps.setString(3, customer_id);
            ps.executeUpdate();
            generate_invoice();
            
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this,"Error"+ex);
        }
        
    }//GEN-LAST:event_jInsertActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        jCustomerID.setText("");
        jOrderID.setText("");
        jTotal.setText("");
    }//GEN-LAST:event_jClearActionPerformed

    private void jShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShowAllActionPerformed
        // TODO add your handling code here:
        ShowOrders form = new ShowOrders();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_jShowAllActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuantityActionPerformed
        // TODO add your handling code here:'
        DefaultTableModel Df1 = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        DefaultTableModel Df3 = (DefaultTableModel) jTable3.getModel();
        int c = Df3.getRowCount();

        try {
            Connection conn = getConnection();
            PreparedStatement ps = conn.prepareStatement("select * from product where ID=?");
            int id = Integer.parseInt(Df1.getValueAt(selectedIndex, 0).toString());
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            rs.next();
            String name = rs.getString("name");
            int price = rs.getInt("price");
            int q = rs.getInt("quantity");
            String Quantity = JOptionPane.showInputDialog("Enter Quantity");
            Integer quantity = Integer.parseInt(Quantity);
            if (quantity <= q) {
                int t = price * quantity;
                JOptionPane.showMessageDialog(null, " quantity entered!");
                Object rowdata[] = new Object[5];
                rowdata[0] = id;
                rowdata[1] = name;
                rowdata[2] = quantity;
                rowdata[3] = price;
                rowdata[4] = t;
                Df3.addRow(rowdata);
                getsum();
                reduce_quantity();
            } else {
                JOptionPane.showMessageDialog(null, "Insufficient quantity"+"\n"+"Go to Products");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jQuantityActionPerformed
  
    private void getsum() {
        int i, sum = 0;
        for (i = 0; i < jTable3.getRowCount(); i++) {
            sum += Integer.parseInt(jTable3.getValueAt(i, 4).toString());
        }
        System.out.println(sum);
        jTotal.setText(Integer.toString(sum));
    }
    
    private void reduce_quantity() {
        DefaultTableModel Df3 = (DefaultTableModel) jTable3.getModel(); 
        
        int selectedIndex = jTable1.getSelectedRow();
            try {
                Connection conn = getConnection();
                PreparedStatement stm=conn.prepareStatement("select * from product where ID=?");
                int id = Integer.parseInt(Df3.getValueAt(selectedIndex, 0).toString());
                stm.setInt(1, id);
                ResultSet rs= stm.executeQuery();
                rs.next();
                int Q=(rs.getInt("quantity")- (Integer) Df3.getValueAt(selectedIndex, 2));
                PreparedStatement ps = conn.prepareStatement("update product set quantity=? where id=?");
                ps.setInt(1, Q);
                ps.setInt(2, id);
                ps.execute();
                System.out.println("The Quantity was reduced to "+Q);
                table_update();
                
            } catch (Exception ex) {
               Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
               
            }
   }
    

    private void table2_update() {
        int c;
        try {
            Connection conn = getConnection();
            PreparedStatement ps = conn.prepareStatement("select * from customerpage");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel) jTable2.getModel();
            Df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for (int a = 0; a < c; a++) {
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("First_Name"));
                    v2.add(rs.getString("Last_Name"));
                    v2.add(rs.getString("Contact"));
                    v2.add(rs.getString("Email"));
                }
                Df.addRow(v2);
            }
            jCustomerID.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void table_update() {
        int c;
        try {
            Connection con = getConnection();
            PreparedStatement ps = con.prepareStatement("select * from product");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
            Df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();

                for (int a = 0; a < c; a++) {
                    v2.add(rs.getString("ID"));
                    v2.add(rs.getString("NAME"));
                    v2.add(rs.getString("PRICE"));
                    v2.add(rs.getString("QUANTITY"));
                    v2.add(rs.getString("DESCRIPTION"));
                    v2.add(rs.getString("CATEGORY"));

                }
                Df.addRow(v2);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Products.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClear;
    private javax.swing.JTextField jCustomerID;
    private javax.swing.JTextField jFullName;
    private javax.swing.JLabel jFullNameLabel;
    private javax.swing.JLabel jFullNameLabel1;
    private javax.swing.JLabel jFullNameLabel2;
    private javax.swing.JLabel jFullNameLabel3;
    private javax.swing.JLabel jFullNameLabel4;
    private javax.swing.JButton jInsert;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jOrderID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jQuantity;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jShowAll;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextPane jTotal;
    // End of variables declaration//GEN-END:variables
}

