/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author sarowar_saurav
 */
public class Users extends javax.swing.JFrame {

    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
        table_update();
    }
    
    public Connection getConnection(){
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/login-database","root","");
            return con;         
        }catch(SQLException e){
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jFullNameLabel = new javax.swing.JLabel();
        jFullName = new javax.swing.JTextField();
        jUsernameLabel5 = new javax.swing.JLabel();
        jLastName = new javax.swing.JTextField();
        jUsernameLabel1 = new javax.swing.JLabel();
        jContact = new javax.swing.JTextField();
        jAddressLabel = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jUsernameLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jInsert = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();
        jClear = new javax.swing.JButton();
        jView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAddress = new javax.swing.JTextArea();
        jUsernameLabel2 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jUsernameLabel3 = new javax.swing.JLabel();
        jConfirm_Password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(51, 0, 51));

        jFullNameLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jFullNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jFullNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jFullNameLabel.setText("First Name :");
        jFullNameLabel.setToolTipText("");

        jFullName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jFullName.setText("first name");
        jFullName.setToolTipText("");
        jFullName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFullNameFocusLost(evt);
            }
        });
        jFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFullNameActionPerformed(evt);
            }
        });

        jUsernameLabel5.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jUsernameLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsernameLabel5.setText("LastName :  ");
        jUsernameLabel5.setToolTipText("");

        jLastName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLastName.setText("lastname");
        jLastName.setToolTipText("");
        jLastName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jLastNameFocusLost(evt);
            }
        });

        jUsernameLabel1.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jUsernameLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsernameLabel1.setText("Contact  :  ");
        jUsernameLabel1.setToolTipText("");

        jContact.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jContact.setText("contact");
        jContact.setToolTipText("");
        jContact.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jContactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jContactFocusLost(evt);
            }
        });

        jAddressLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jAddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        jAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jAddressLabel.setText("Address  :");
        jAddressLabel.setToolTipText("");

        jUsername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jUsername.setText("Username");
        jUsername.setToolTipText("");
        jUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jUsernameFocusLost(evt);
            }
        });
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });

        jUsernameLabel.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jUsernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsernameLabel.setText("Username :");
        jUsernameLabel.setToolTipText("");

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setAutoscrolls(true);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(51, 0, 51));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 4));
        jTable2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Full Name", "Last Name", "Password", "Contact", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setToolTipText("");
        jTable2.setColumnSelectionAllowed(true);
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(40);
        jTable2.setRowMargin(4);
        jTable2.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jTable2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.setShowGrid(true);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jScrollPane4.setViewportView(jScrollPane3);

        jInsert.setBackground(new java.awt.Color(255, 204, 204));
        jInsert.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jInsert.setText("Insert");
        jInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertActionPerformed(evt);
            }
        });

        jDelete.setBackground(new java.awt.Color(255, 204, 204));
        jDelete.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jUpdate.setBackground(new java.awt.Color(255, 204, 204));
        jUpdate.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jUpdate.setText("Update");
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        jClear.setBackground(new java.awt.Color(255, 204, 204));
        jClear.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jClear.setText("Clear");
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });

        jView.setBackground(new java.awt.Color(255, 204, 204));
        jView.setFont(new java.awt.Font("Bebas Kai", 0, 14)); // NOI18N
        jView.setText("View");
        jView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewActionPerformed(evt);
            }
        });

        jAddress.setColumns(20);
        jAddress.setRows(5);
        jScrollPane1.setViewportView(jAddress);

        jUsernameLabel2.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jUsernameLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsernameLabel2.setText("Password :  ");
        jUsernameLabel2.setToolTipText("");

        jPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPassword.setText("password");
        jPassword.setToolTipText("");
        jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFocusLost(evt);
            }
        });

        jUsernameLabel3.setFont(new java.awt.Font("BatangChe", 1, 18)); // NOI18N
        jUsernameLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jUsernameLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jUsernameLabel3.setText("Retype   :");
        jUsernameLabel3.setToolTipText("");

        jConfirm_Password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jConfirm_Password.setText("password");
        jConfirm_Password.setToolTipText("");
        jConfirm_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jConfirm_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jConfirm_PasswordFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jUsernameLabel)
                    .addComponent(jFullNameLabel)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jUsernameLabel5)
                                .addComponent(jUsernameLabel1))
                            .addComponent(jAddressLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsernameLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUsernameLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jContact)
                                    .addComponent(jUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(jLastName)
                                    .addComponent(jFullName)
                                    .addComponent(jPassword)
                                    .addComponent(jConfirm_Password)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jView, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFullNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jConfirm_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jUsernameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jContact, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jClear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Connection conn;
    PreparedStatement ps;
    private void jFullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFullNameFocusGained
        // TODO add your handling code here:
        if(jFullName.getText().trim().toLowerCase().equals("fullname"))
        {
            jFullName.setText("");
            jFullName.setForeground(Color.black);
        }
    }//GEN-LAST:event_jFullNameFocusGained

    private void jFullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFullNameFocusLost
        // TODO add your handling code here:
        if(jFullName.getText().trim().equals("") ||
            jFullName.getText().trim().toLowerCase().equals("fullname"))
        {
            jFullName.setText("fullname");
            jFullName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jFullNameFocusLost

    private void jLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLastNameFocusGained
        // TODO add your handling code here:
        if(jLastName.getText().trim().toLowerCase().equals("lastname"))
        {
            jLastName.setText("");
            jLastName.setForeground(Color.black);
        }
    }//GEN-LAST:event_jLastNameFocusGained

    private void jLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLastNameFocusLost
        // TODO add your handling code here:
        if(jLastName.getText().trim().equals("") ||
            jLastName.getText().trim().toLowerCase().equals("lastname"))
        {
            jLastName.setText("lastname");
            jLastName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jLastNameFocusLost

    private void jContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jContactFocusGained
        // TODO add your handling code here:
        if(jContact.getText().trim().toLowerCase().equals("contact"))
        {
            jContact.setText("");
            jContact.setForeground(Color.black);
        }
    }//GEN-LAST:event_jContactFocusGained

    private void jContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jContactFocusLost
        // TODO add your handling code here:
        if(jContact.getText().trim().equals("") ||
            jContact.getText().trim().toLowerCase().equals("contact"))
        {
            jContact.setText("contact");
            jContact.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jContactFocusLost

    private void jUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusGained
        // TODO add your handling code here:
        if(jUsername.getText().trim().toLowerCase().equals("Username"))
        {
            jUsername.setText("");
            jUsername.setForeground(Color.black);
        }
    }//GEN-LAST:event_jUsernameFocusGained

    private void jUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUsernameFocusLost
        // TODO add your handling code here:
        if(jUsername.getText().trim().equals("") ||
            jUsername.getText().trim().toLowerCase().equals("Username"))
        {
            jUsername.setText("Username");
            jUsername.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jUsernameFocusLost

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseClicked
   
    public boolean verifyFields(){
        String full_name = jFullName.getText();
        String last_name = jLastName.getText();
        String username = jUsername.getText();
        String password = String.valueOf(jPassword.getPassword());
        String confirm_password = String.valueOf(jConfirm_Password.getPassword());
        String contact = jContact.getText();
        String address = jAddress.getText();
        
        // check empty fields
        if(full_name.trim().equals("") || last_name.trim().equals("") || username.trim().equals("") || contact.trim().equals("")
           || password.trim().equals("") || confirm_password.trim().equals("") || address.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null, "One Or More Fields Are Empty","Empty Fields",2);
            return false;
        }
        
        // check if the two password are equals or not
        else if(!password.equals(confirm_password))
        {
           JOptionPane.showMessageDialog(null, "Password Doesn't Match","Confirm Password",2); 
           return false;
        }
        
        // if everything is ok
        else{
            return true;
        }
    }
    
    public boolean checkUsername(String username){
        
        PreparedStatement st;
        ResultSet rs;
        boolean username_exist = false;
        
        String query = "SELECT * FROM `loginpage` WHERE `username` = ?";
        
        try {
            Connection con = getConnection();
            st = con.prepareStatement(query);
            st.setString(1, username);
            rs = st.executeQuery();
        
            if(rs.next())
            {
                username_exist = true;
                JOptionPane.showMessageDialog(null, "This Username is Already Taken, Choose Another One", "Username Failed", 2);
            }
            
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        return username_exist;
    }
    
    private void jInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertActionPerformed
        // TODO add your handling code here:
        String full_name = jFullName.getText();
        String last_name = jLastName.getText();
        String username = jUsername.getText();
        String password = String.valueOf(jPassword.getPassword());
        String confirm_password = String.valueOf(jConfirm_Password.getPassword());
        String contact = jContact.getText();
        String address = jAddress.getText();
        try {
// check if the data are empty
         if(verifyFields())
         {
// check if the username already exists
             if(!checkUsername(username))
             {
                ResultSet rs;
                String registerUserQuery = "INSERT INTO `loginpage`(`full_name`, `last_name`, `username`, `password`, `confirm_password`, `contact`, `address`) VALUES(?,?,?,?,?,?,?)";
                try{
                    ps = conn.prepareStatement(registerUserQuery);
                    ps.setString(1, full_name);
                    ps.setString(2, last_name);
                    ps.setString(3, username);
                    ps.setString(4, password);
                    ps.setString(5, confirm_password);
                    ps.setString(6, contact);
                    ps.setString(7, address);                    
                    if(ps.executeUpdate() != 0){
                        JOptionPane.showMessageDialog(null, "Account Has Been Created");
                        table_update();
                    }else{
                        JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                    }
                
                }
                catch (HeadlessException | SQLException e){
                     JOptionPane.showMessageDialog(null, e);
                }
             }
         }
          conn.close();
            
        }
        catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
            JOptionPane.showMessageDialog(this,"Error"+e);
        }

    }//GEN-LAST:event_jInsertActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        try {
            String username = jUsername.getText();

            int dialogResult=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO DELETE THE RECORD","WARNING",JOptionPane.YES_NO_OPTION);

            if(dialogResult==JOptionPane.YES_OPTION)
            {
                conn = getConnection();
                ps = conn.prepareStatement("delete from loginpage where username=?");

                ps.setString(1, username);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(this,"Record deleted");
                table_update();

                jUsername.setText("");
                jFullName.setText("");
                jLastName.setText("");
                jPassword.setText("");
                jConfirm_Password.setText("");
                jContact.setText("");
                jAddress.setText("");

                jUsername.requestFocus();
            }
        }catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error"+ex);
        }
    }//GEN-LAST:event_jDeleteActionPerformed

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        // TODO add your handling code here:
        try {
        String full_name = jFullName.getText();
        String last_name = jLastName.getText();
        String username = jUsername.getText();
        String password = String.valueOf(jPassword.getPassword());
        String confirm_password = String.valueOf(jConfirm_Password.getPassword());
        String contact = jContact.getText();
        String address = jAddress.getText();
            conn = getConnection();
            ps = conn.prepareStatement("update loginpage set full_name=?,last_name=?,password =?, confirm_password=?, Contact=?, address=? where username=?");
            ps.setString(1, full_name);
            ps.setString(2, last_name);
            ps.setString(3, password);
            ps.setString(4, confirm_password);
            ps.setString(5, contact);
            ps.setString(6, address); 
            ps.setString(7, username);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this,"Record Updated");
            table_update();

            jUsername.setText("");
            jFullName.setText("");
            jLastName.setText("");
            jPassword.setText("");
            jConfirm_Password.setText(""); 
            jContact.setText("");
            jAddress.setText("");
            jUsername.requestFocus();
        }
        catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Error"+ex);
        }
    }//GEN-LAST:event_jUpdateActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        // TODO add your handling code here:
            jUsername.setText("");
            jFullName.setText("");
            jLastName.setText("");
            jPassword.setText("");
            jConfirm_Password.setText(""); 
            jContact.setText("");
            jAddress.setText("");
            jUsername.requestFocus();

        jUsername.requestFocus();
    }//GEN-LAST:event_jClearActionPerformed

    private void jViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel Df = (DefaultTableModel)jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();

        jUsername.setText(Df.getValueAt(selectedIndex,0).toString());
        jFullName.setText(Df.getValueAt(selectedIndex,1).toString());
        jLastName.setText(Df.getValueAt(selectedIndex,2).toString());
        jPassword.setText(Df.getValueAt(selectedIndex,3).toString());
        jConfirm_Password.setText(Df.getValueAt(selectedIndex,3).toString());
        jContact.setText(Df.getValueAt(selectedIndex,4).toString());
        jAddress.setText(Df.getValueAt(selectedIndex,5).toString());
        
    }//GEN-LAST:event_jViewActionPerformed

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(jPassword.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            jPassword.setText("");
            jPassword.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordFocusGained

    private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(jPassword.getPassword());
        if(pass.trim().equals("") ||
            pass.trim().toLowerCase().equals("password"))
        {
            jPassword.setText("password");
            jPassword.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_jPasswordFocusLost

    private void jConfirm_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jConfirm_PasswordFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(jConfirm_Password.getPassword());
        if(pass.trim().toLowerCase().equals("password"))
        {
            jConfirm_Password.setText("");
            jConfirm_Password.setForeground(Color.black);
        }
    }//GEN-LAST:event_jConfirm_PasswordFocusGained

    private void jConfirm_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jConfirm_PasswordFocusLost
        // TODO add your handling code here:
        String pass = String.valueOf(jConfirm_Password.getPassword());
        if(pass.trim().equals("") ||
            pass.trim().toLowerCase().equals("password"))
        {
            jConfirm_Password.setText("password");
            jConfirm_Password.setForeground(new Color(153,153,153));

        }
    }//GEN-LAST:event_jConfirm_PasswordFocusLost

    private void jFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFullNameActionPerformed
    
    private void table_update()
        {
            int c;
            try {
            conn = getConnection();
            ps = conn.prepareStatement("select * from loginpage");
            ResultSet rs = ps.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)jTable2.getModel();
            Df.setRowCount(0);
            while(rs.next())
            {
                Vector v2 = new Vector();
                for(int a=0; a<c; a++) 
                {
                    v2.add(rs.getString("Username"));
                    v2.add(rs.getString("full_name"));
                    v2.add(rs.getString("last_name"));
                    v2.add(rs.getString("password"));
                    v2.add(rs.getString("contact"));
                    v2.add(rs.getString("address"));
                }
                Df.addRow(v2);
            }
            jUsername.setText("");
            jFullName.setText("");
            jLastName.setText("");
            jPassword.setText("");
            jConfirm_Password.setText(""); 
            jContact.setText("");
            jAddress.setText("");
            jUsername.requestFocus();  
        }     
        catch (SQLException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);            
            JOptionPane.showMessageDialog(this,"Error"+ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAddress;
    private javax.swing.JLabel jAddressLabel;
    private javax.swing.JButton jClear;
    private javax.swing.JPasswordField jConfirm_Password;
    private javax.swing.JTextField jContact;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jFullName;
    private javax.swing.JLabel jFullNameLabel;
    private javax.swing.JButton jInsert;
    private javax.swing.JTextField jLastName;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jUpdate;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel jUsernameLabel;
    private javax.swing.JLabel jUsernameLabel1;
    private javax.swing.JLabel jUsernameLabel2;
    private javax.swing.JLabel jUsernameLabel3;
    private javax.swing.JLabel jUsernameLabel5;
    private javax.swing.JButton jView;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
